### ISSUE TITLE
cython wrappers for python?

### ISSUE THREAD

**Issue by rabernat** [dengwirda/jigsaw-geo-matlab#11]
Hi @dengwirda...just getting up to speed on jigsaw. Thanks for this amazing package!

Us python users would love a python API to jigsaw-geo. Wrapping c++ libraries for python is very common and easy to do thanks to cython. Here are some instructions on how this works:
https://github.com/cython/cython/wiki/WrappingCPlusPlus

I'm wondering if you have considered doing this or if someone else has done it already. @toddringler mentioned that they use python to interact with jigsaw. I would consider spending some time on it myself, but I don't want to repeat effort that has already been done elsewhere.

Thanks again for contributing this fantastic tool to our community.

**Comment by dengwirda** [comment]
Hi @rabernat,

It would be great to pursue a proper Python interface for JIGSAW. It's been on my list for a little while, but I've just never gotten around to it. My own Python skills are somewhat lacking here, so if you were interested in working with me on this it would be a big help.

Presently, it's possible to compile JIGSAW in two ways: as a command-line executable that you interact with via text files, or as a static/dynamic library that comes with a C-style API. If I understand correctly, this second approach might be a good way of enabling Python support.

I'll send you an email on the details here, but the short answer is: Yes! Let's do this.

**Comment by toddringler** [comment]
Maybe check with @pwolfram -- he might have something to contribute.

**Comment by pwolfram** [comment]
Currently we are using the standard matlab workflow to access and run jigsaw, but do use python for the rest of the workflow.  Having the entire workflow entirely in python would be a huge blessing but has not yet been elevated in priority yet to be accomplished on our end.  Glad to see there is some cross-community inertia forming!

**Comment by pwolfram** [comment]
@rabernat, what is your target model application?  We have the full workflow for MPAS-O in a currently open PR in MPAS-Tools that was your end goal.

**Comment by dengwirda** [comment]
Yes, definitely @toddringler, @pwolfram: my preference would be to add to the community JIGSAW tools here, and to try to offer the full functionality of the MATLAB interface direct in Python. 

The C-style API is something that I added toward the end of last year to interface with the CSIRO coastal model (COMPAS). It would be great to leverage it for improved Python support. If it's possible to achieve pre- and post-processing + visualisation in Python I think this would be really useful.

**Comment by dengwirda** [comment]
A proper `python` interface to `jigsaw` is now (finally!) available via [jigsaw-python](https://github.com/dengwirda/jigsaw-python/). A set of examples for GCM-type applications can be found [here](https://github.com/dengwirda/jigsaw-geo-python).
