### ISSUE TITLE
proper system installation scripts

### ISSUE THREAD

**Issue by rabernat** [dengwirda/jigsaw-geo-matlab#13]
As I work on #12, I am realizing that it would be simplest to separate the python wrapper from the library itself.

What would be ideal would be for this package to have a standard build process to install both the executable and the libraries in a system-wide location via `make install`. Then the cython code could link to those libraries and not have to worry about hacking the linking process.

Is this something you would consider providing?

**Comment by dengwirda** [comment]
Yes, I'm happy to look into this. JIGSAW's 'build process' is essentially just a one-liner in g++ (there are no complex dependencies or whatnot). The only potential issue - I think - is Windows support. JIGSAW will compile with MSVC, but I'll need to think a little harder re. automated make scripts...

Thanks for your work on this! I'm just scrambling around with some other things over the next few days, but will try to look at this over the weekend / early next week.

**Comment by rabernat** [comment]
No worries. Not urgent. [Autotools](https://robots.thoughtbot.com/the-magic-behind-configure-make-make-install) is probably the easiest way to provide the standard `./configure.sh; make; make install` experience. Since, as you say, there are no dependencies, it should be pretty straightforward to set up.

It would be nice to build both the library and executable in one go. 

For now, I am manually copying the shared library into /usr/local/lib so cython can find it. This is obviously not a robust way to distribute the software.

**Comment by brey** [comment]
I don't know if it is relevant but, as I suggested to @dengwirda, one other way would be to use conda. I am using jigsaw for grid generation in my python-based project and that would make my life considerably easier.

**Comment by dengwirda** [comment]
[jigsaw-python](https://github.com/dengwirda/jigsaw-python) can now be installed via both `cmake` or `conda` type workflows.
