### ISSUE TITLE
Incorrect number of mesh points in output file

### ISSUE THREAD

**Issue by ktritz** [dengwirda/jigsaw-geo-matlab#28]
Using: jigsaw-geo64r.exe
downloaded from archive: dengwirda-jigsaw-geo-matlab-66d396d (zenodo)

Running the example for the uniform geo mesh at 150, 30, 20, 10km spacings, the number of points specified in the output file (points=N) does not match the actual number of points listed in the text file. Not sure if there is a similar problem with the listed number of triangles.

**Comment by ktritz** [comment]
Thanks, I was able to build the new code with Visual Studio, but the old
geometry files don't work for the uniform earth grid. The files for
meshdemom: Demo4 don't seem to be in the geo directory.

EARTH-CONST-GEOM.msh

**Comment by dengwirda** [comment]
@ktritz those files are typically created by running the `MATLAB` scripts. If you're trying to run from the cmd-line direct, there's also some information about file formats [here](https://github.com/dengwirda/jigsaw/wiki). If you are running via `MATLAB`, `meshdemo.m` contains a set of examples to get started with.
